# Generated by Django 4.2.27 on 2026-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
