# Generated by Django 4.2.27 on 2026-02-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
