# Generated by Django 4.2.27 on 2026-02-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='mood',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light'), ('Comedy', 'Comedy'), ('Emotional', 'Emotional'), ('Mysterious', 'Mysterious'), ('Inspiring', 'Inspiring')], default='Light', max_length=20),
        ),
    ]
