# Generated by Django 4.2.27 on 2026-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='community',
            name='mood',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light'), ('Comedy', 'Comedy'), ('Emotional', 'Emotional'), ('Mysterious', 'Mysterious'), ('Inspiring', 'Inspiring'), ('Romantic', 'Romantic'), ('Adventure', 'Adventure')], default='Light', max_length=20),
        ),
    ]
