# Generated by Django 4.2.27 on 2026-02-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_category_community_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='mood',
        ),
    ]
