# Generated by Django 4.2.27 on 2026-02-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_remove_community_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar_icon',
            field=models.CharField(default='🌎', max_length=10),
        ),
    ]
