# Generated by Django 4.2.27 on 2026-02-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_community_avatar_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='privacy',
        ),
    ]
