# Generated by Django 4.2.27 on 2026-04-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_communityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community_profiles/'),
        ),
    ]
