# Generated by Django 4.2.27 on 2026-04-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_community_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='avatar_icon',
        ),
    ]
