# Generated by Django 4.2.27 on 2026-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='color_vibe',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.CreateModel(
            name='MediaMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV'), ('anime', 'Anime')], max_length=10)),
                ('moods', models.ManyToManyField(related_name='media_items', to='moods.mood')),
            ],
            options={
                'unique_together': {('media_id', 'media_type')},
            },
        ),
    ]
